 name: CI Pipeline

on:
  push:
    branches:
      - '**'


            jobs:
  build:
    runs-on: ubuntu-24.04  # Use the specific version
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Gradle
        run: ./gradlew build
      - name: Run Tests
        run: ./gradlew test

